"""Generates ANSWER_KEY.md from engine/defects.py, so the answer key can
never drift from the code that actually implements it.

Usage:
    conda run -n learning python scripts/generate_answer_key.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from engine.defects import ALL_DEFECT_IDS, DefectFlags, INVARIANT_INVISIBLE, INVARIANT_VISIBLE


def _header() -> str:
    n = len(ALL_DEFECT_IDS)
    n_visible = len(INVARIANT_VISIBLE)
    n_invisible = len(INVARIANT_INVISIBLE)
    return f"""# Answer key

Generated by `scripts/generate_answer_key.py` from `engine/defects.py` --
do not hand-edit this file; edit the docstrings on `DefectFlags` fields
instead and regenerate. This is included in the repo for transparency, per
the project plan: the point of a differential oracle and an invariant
checker is that grading doesn't depend on anyone having memorized this
list, but the list itself should still be a first-class, auditable
artifact rather than a private note.

{n} defects, each gated by exactly one boolean flag in `DefectFlags`
(all default `False` -- clean/correct behavior). {n_visible} are visible
to the invariant checker (`engine/invariants.py`) on their own; {n_invisible}
are not, and finding those is where an exploration strategy actually has
to earn its keep -- see RESULTS.md for the trigger-vs-detection numbers
this split produces per method.

"""


def main() -> None:
    lines = [_header()]
    for defect_id, field_name in sorted(ALL_DEFECT_IDS.items()):
        doc = DefectFlags.model_fields[field_name].description or ""
        visible = "invariant-visible" if defect_id in INVARIANT_VISIBLE else "invariant-invisible"
        lines.append(f"## {defect_id} -- `{field_name}` ({visible})\n\n{doc}\n")
    (ROOT / "ANSWER_KEY.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {ROOT / 'ANSWER_KEY.md'}")


if __name__ == "__main__":
    main()
